<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyKinhDoanh" Class="QLKDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LGVN13311-XPB01\SQLEXPRESS;Initial Catalog=QuanLyKinhDoanh;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QuanLyKinhDoanhConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChietKhau" Member="ChietKhaus">
    <Type Name="ChietKhau">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdKhachHangGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KhachHangGroup_ChietKhau" Member="KhachHangGroup" ThisKey="IdKhachHangGroup" OtherKey="Id" Type="KhachHangGroup" IsForeignKey="true" />
      <Association Name="SanPham_ChietKhau" Member="SanPham" ThisKey="IdSanPham" OtherKey="Id" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XuatXu" Member="XuatXus">
    <Type Name="XuatXu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="XuatXu_SanPham" Member="SanPhams" ThisKey="Id" OtherKey="IdXuatXu" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHoaDon" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="IdType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_HoaDonDetail" Member="HoaDonDetails" ThisKey="Id" OtherKey="IdHoaDon" Type="HoaDonDetail" />
      <Association Name="HoaDonStatus_HoaDon" Member="HoaDonStatus" ThisKey="IdStatus" OtherKey="Id" Type="HoaDonStatus" IsForeignKey="true" />
      <Association Name="HoaDonType_HoaDon" Member="HoaDonType" ThisKey="IdType" OtherKey="Id" Type="HoaDonType" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="IdKhachHang" OtherKey="Id" Type="KhachHang" IsForeignKey="true" />
      <Association Name="User_HoaDon" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonDetail" Member="HoaDonDetails">
    <Type Name="HoaDonDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdHoaDon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChietKhau" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_HoaDonDetail" Member="HoaDon" ThisKey="IdHoaDon" OtherKey="Id" Type="HoaDon" IsForeignKey="true" />
      <Association Name="SanPham_HoaDonDetail" Member="SanPham" ThisKey="IdSanPham" OtherKey="Id" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonStatus" Member="HoaDonStatus">
    <Type Name="HoaDonStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HoaDonStatus_HoaDon" Member="HoaDons" ThisKey="Id" OtherKey="IdStatus" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonType" Member="HoaDonTypes">
    <Type Name="HoaDonType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Association Name="HoaDonType_HoaDon" Member="HoaDons" ThisKey="Id" OtherKey="IdType" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgayCap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NoiCap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TichLuy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="Id" OtherKey="IdKhachHang" Type="HoaDon" />
      <Association Name="KhachHangGroup_KhachHang" Member="KhachHangGroup" ThisKey="IdGroup" OtherKey="Id" Type="KhachHangGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHangGroup" Member="KhachHangGroups">
    <Type Name="KhachHangGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="KhachHangGroup_ChietKhau" Member="ChietKhaus" ThisKey="Id" OtherKey="IdKhachHangGroup" Type="ChietKhau" />
      <Association Name="KhachHangGroup_KhachHang" Member="KhachHangs" ThisKey="Id" OtherKey="IdGroup" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdXuatXu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GiaMua" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LaiSuat" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Hieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiHan" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DonViThoiHan" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="ThoiGianBaoHanh" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DonViBaoHanh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_ChietKhau" Member="ChietKhaus" ThisKey="Id" OtherKey="IdSanPham" Type="ChietKhau" />
      <Association Name="SanPham_HoaDonDetail" Member="HoaDonDetails" ThisKey="Id" OtherKey="IdSanPham" Type="HoaDonDetail" />
      <Association Name="XuatXu_SanPham" Member="XuatXu" ThisKey="IdXuatXu" OtherKey="Id" Type="XuatXu" IsForeignKey="true" />
      <Association Name="SanPhamGroup_SanPham" Member="SanPhamGroup" ThisKey="IdGroup" OtherKey="Id" Type="SanPhamGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPhamGroup" Member="SanPhamGroups">
    <Type Name="SanPhamGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="SanPhamGroup_SanPham" Member="SanPhams" ThisKey="Id" OtherKey="IdGroup" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DeleteFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_HoaDon" Member="HoaDons" ThisKey="Id" OtherKey="IdUser" Type="HoaDon" />
      <Association Name="UserGroup_User" Member="UserGroup" ThisKey="IdGroup" OtherKey="Id" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroup" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="UserGroup_User" Member="Users" ThisKey="Id" OtherKey="IdGroup" Type="User" />
    </Type>
  </Table>
</Database>